GET http://localhost:3000/product

###
POST http://localhost:3000/product
Content-Type: application/json

{
    "name": "realme 6",
    "price": 15000
}

###
GET http://localhost:3000/product/6736c008f1138cdbd988a4e1

###
PATCH http://localhost:3000/product/6736c008f1138cdbd988a4e1
Content-Type: application/json

{
    "name": "",
    "price": 19000
}

###
DELETE http://localhost:3000/product/671381baa3fc361a10acdd99

//test api
###
POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "oppo",
    "price": 2999
}

###
GET http://localhost:3000/abcd